# Generated by Django 5.1.2 on 2024-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girlchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
